### PR TITLE
Application - Daily-Coding-DS-ALGO-Practice

### PR DESCRIPTION
**Pull request by Ayush7614**
## Project Application
Hack Club SRM is elated to have you submit your Project Proposal! Let's get started! 🎉

I am 🤝:
 - [x] A Prospective Mentor
 - [ ] Representing an Organization

Checklist ✅:
 - [x] I have read the [Code of Conduct](https://github.com/Hack-Club-SRM/Code-of-Conduct) of Hack Club SRM.
 - [x] I have only made changes to the `project_proposals` folder.
 - [ ] I am open for feedback and comments over my Proposal.
 - [ ] I will be able to devote *at least* an hour a day assisting participants if shortlisted for HCSSoC.
 - [x] I have filled out all the fields in my application.

### CODE REVIEW

**Review by aaishikasb — APPROVED** [review]
Hey @Ayush7614!
Elated to have you as a prospective mentor! Will it be convenient for you to remove Bundli-Frontend.md from the root folder?

**Comment by aaishikasb** [comment]
Thanks for the changes, PR is approved!

**Comment by Ayush7614** [comment]
> Hey @Ayush7614!
> Elated to have you as a prospective mentor! Will it be convenient for you to remove Bundli-Frontend.md from the root folder?

Done Sir

**Comment by Ayush7614** [comment]
@aaishikasb any updates regarding HSSOC

**Comment by aaishikasb** [comment]
Hey @Ayush7614, Mentor Registrations are over now. I'll merge your Pull Request and we'll get started with Student Registrations.

**Pull request merged**
